import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# MoTune mmBERT with Within-Exit Partitioned InfoNCE (WEP-InfoNCE)\n",
            "\n",
            "This notebook runs dedicated training for the **MoTune Two-Stream Bi-Encoder** equipped with **Within-Exit Partitioned InfoNCE (WEP-InfoNCE)** on Kaggle GPU, and automatically pushes checkpoints and metrics to Hugging Face Hub.\n",
            "\n",
            "### Method Details\n",
            "- **Within-Exit Partitioning**: Strict block-diagonal exit masking guarantees off-diagonal contrastive negatives are drawn from the same constituent exit role (no exit-identity shortcut).\n",
            "- **Per-Exit Positive Weighting**: Continuous min-max weighting based on gold literalness ratings.\n",
            "- **Shared Metric Projector**: 2-layer MLP head (768 -> 768 -> 768, LayerNorm, GELU) projecting hidden states $h$ to metric vectors $z$.\n",
            "- **Dual Diagnostic Alignment**: Evaluates raw cosine similarity $\\rho(h)$ alongside projected metric cosine similarity $\\rho(z)$.\n",
            "\n",
            "### Kaggle Setup Instructions\n",
            "1. Set Accelerator to **GPU (T4 x2 or P100)**.\n",
            "2. Under **Settings -> Secrets**, add:\n",
            "   - `HF_TOKEN`: Your Hugging Face write token.\n",
            "   - `GITHUB_TOKEN`: (Optional) GitHub personal access token if cloning a private repo.\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 1: Environment & Repository Initialization\n",
            "import os, sys, subprocess\n",
            "from pathlib import Path\n",
            "\n",
            "os.environ['CUDA_VISIBLE_DEVICES'] = '0'\n",
            "os.environ.setdefault('PYTORCH_ALLOC_CONF', 'expandable_segments:True')\n",
            "\n",
            "def _env_or_secret(name: str, default: str = '') -> str:\n",
            "    v = os.environ.get(name, '')\n",
            "    if v:\n",
            "        return v\n",
            "    try:\n",
            "        from kaggle_secrets import UserSecretsClient\n",
            "        return UserSecretsClient().get_secret(name)\n",
            "    except Exception:\n",
            "        return default\n",
            "\n",
            "# Repository source configuration\n",
            "REPO_URL = os.environ.get('REPO_URL', 'https://github.com/AmnO-O/MoTune.git')\n",
            "REPO_BRANCH = os.environ.get('REPO_BRANCH', 'main')\n",
            "GITHUB_TOKEN = _env_or_secret('GITHUB_TOKEN', '')\n",
            "\n",
            "dest = Path('/kaggle/working/MoTune')\n",
            "url = REPO_URL\n",
            "if GITHUB_TOKEN and 'https://' in url:\n",
            "    url = url.replace('https://', f'https://{GITHUB_TOKEN}@')\n",
            "\n",
            "if Path('src/run.py').is_file():\n",
            "    REPO = Path('.').resolve()\n",
            "    print('Using current local repository at:', REPO)\n",
            "elif (dest / 'src' / 'run.py').is_file() and not (dest / '.git').is_dir():\n",
            "    REPO = dest\n",
            "    print('Using uploaded directory at:', REPO)\n",
            "elif (dest / '.git').is_dir():\n",
            "    print('Refreshing git clone at:', dest)\n",
            "    try:\n",
            "        subprocess.run(['git', '-C', str(dest), 'fetch', '--depth', '1', 'origin', REPO_BRANCH], check=True)\n",
            "        subprocess.run(['git', '-C', str(dest), 'reset', '--hard', f'origin/{REPO_BRANCH}'], check=True)\n",
            "    except Exception as e:\n",
            "        print('Git refresh failed or offline, using local copy:', e)\n",
            "    REPO = dest\n",
            "else:\n",
            "    print(f'Cloning {REPO_URL} (branch: {REPO_BRANCH})...')\n",
            "    subprocess.run(['git', 'clone', '--depth', '1', '--branch', REPO_BRANCH, url, str(dest)], check=True)\n",
            "    REPO = dest\n",
            "\n",
            "os.chdir(REPO)\n",
            "print('Working directory:', REPO)\n",
            "\n",
            "# Ensure dependencies exist\n",
            "for pkg in ['torch', 'transformers', 'huggingface_hub', 'pandas', 'numpy', 'scikit-learn', 'scipy', 'pyyaml']:\n",
            "    try:\n",
            "        __import__(pkg.replace('-', '_'))\n",
            "    except ImportError:\n",
            "        print(f'Installing {pkg}...')\n",
            "        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', pkg], check=False)\n",
            "\n",
            "print('Environment initialized successfully.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 2: Configuration & Staged Training Setup\n",
            "import os, sys\n",
            "from pathlib import Path\n",
            "\n",
            "# Choose training stage:\n",
            "# - 'phase0'    : Pure WEP-InfoNCE representation pretraining (backbone & heads frozen, trains projector on Exit 0, 1, 2)\n",
            "# - 'full'      : Standard Warm-LoRA multi-task training (Phase 1 heads + Phase 2 LoRA)\n",
            "# - 'downstream': Downstream scoring initialized from pre-trained Phase 0 checkpoint (load_from='models/best.pt')\n",
            "STAGE = os.environ.get('TRAINING_STAGE', 'phase0')\n",
            "\n",
            "CONFIG_MAP = {\n",
            "    'phase0': 'config/proto_stream_phase0.json',\n",
            "    'full': 'config/proto_stream_wep_infonce.json',\n",
            "    'downstream': 'config/proto_stream_downstream_after_phase0.json',\n",
            "}\n",
            "CONFIG_FILE = CONFIG_MAP.get(STAGE, 'config/proto_stream_phase0.json')\n",
            "\n",
            "# Hugging Face target model repository (change to your HF account/repo)\n",
            "DEFAULT_HF_REPO = f'AmnO-O/motune-wep-{STAGE}'\n",
            "HF_REPO_ID = os.environ.get('HF_REPO_ID', DEFAULT_HF_REPO)\n",
            "HF_PRIVATE = os.environ.get('HF_PRIVATE', 'true').lower() not in ('0', 'false', 'no')\n",
            "\n",
            "# Base overrides for Kaggle environment\n",
            "OVERRIDES = {\n",
            "    'batch_size': '32',\n",
            "    'accum_steps': '1',\n",
            "    'num_workers': '0',        # 0 prevents multiprocessing deadlocks on Kaggle\n",
            "}\n",
            "\n",
            "if STAGE == 'phase0':\n",
            "    OVERRIDES.update({\n",
            "        'phase0_only': 'true',\n",
            "        'supervised_loss_weight': '0.0',\n",
            "        'wep_weight': '1.0',\n",
            "        'freeze_epochs': '2',        # 2 epochs warmup for projector on frozen backbone\n",
            "        'lora_epochs': '18',         # 18 epochs LoRA contrastive pretraining on layers >= 18\n",
            "        'lora_from_layer': '18',     # Exit layers: 18 (Mod), 19 (Head), 20-21 (PV)\n",
            "        'head_lr': '3e-4',\n",
            "        'encoder_lr': '8e-6',\n",
            "    })\n",
            "\n",
            "def get_training_command():\n",
            "    cmd = [sys.executable, '-m', 'src.run', '--device', 'cuda', '--config', CONFIG_FILE]\n",
            "    for k, v in OVERRIDES.items():\n",
            "        if v not in (None, ''):\n",
            "            cmd.extend(['--set', f'{k}={v}'])\n",
            "    return cmd\n",
            "\n",
            "print(f'Training stage active: [{STAGE.upper()}] using config: {CONFIG_FILE}')\n",
            "print('Command:', ' '.join(get_training_command()))\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 3: Execute Model Training with Live Diagnostic Logs\n",
            "import subprocess\n",
            "\n",
            "cmd = get_training_command()\n",
            "print('=' * 75)\n",
            "print('>>> LAUNCHING WEP-InfoNCE TRAINING...')\n",
            "print('=' * 75)\n",
            "\n",
            "proc = subprocess.Popen(\n",
            "    cmd,\n",
            "    cwd=str(REPO),\n",
            "    stdout=subprocess.PIPE,\n",
            "    stderr=subprocess.STDOUT,\n",
            "    text=True,\n",
            "    bufsize=1\n",
            ")\n",
            "\n",
            "for line in proc.stdout:\n",
            "    print(line, end='', flush=True)\n",
            "\n",
            "proc.wait()\n",
            "if proc.returncode != 0:\n",
            "    raise RuntimeError(f'Training exited with code {proc.returncode}')\n",
            "print('\\n>>> Training finished successfully!')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 4: Inspect Metrics & Validation Correlation Summary\n",
            "import json\n",
            "from pathlib import Path\n",
            "\n",
            "work = Path('/kaggle/working')\n",
            "for cand in [work / 'metrics.json', REPO / 'metrics.json', REPO / 'output' / 'metrics.json', Path('metrics.json')]:\n",
            "    if cand.is_file():\n",
            "        print(f'--- Metrics found at {cand} ---')\n",
            "        data = json.loads(cand.read_text(encoding='utf-8'))\n",
            "        print(json.dumps(data, indent=2))\n",
            "        break\n",
            "else:\n",
            "    print('metrics.json not found yet.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 5: Push Trained Checkpoints & Artifacts to Hugging Face Hub\n",
            "from pathlib import Path\n",
            "from huggingface_hub import HfApi\n",
            "\n",
            "token = _env_or_secret('HF_TOKEN', '')\n",
            "if not token:\n",
            "    print('ERROR: HF_TOKEN secret not found! Add HF_TOKEN under Kaggle Add-ons -> Secrets.')\n",
            "elif not HF_REPO_ID:\n",
            "    print('ERROR: HF_REPO_ID is empty! Please set HF_REPO_ID in Cell 2.')\n",
            "else:\n",
            "    print(f'Initializing Hugging Face Hub API for target repo: {HF_REPO_ID} (private={HF_PRIVATE})')\n",
            "    api = HfApi(token=token)\n",
            "    api.create_repo(repo_id=HF_REPO_ID, private=HF_PRIVATE, exist_ok=True, repo_type='model')\n",
            "    \n",
            "    # 1. Upload model checkpoint files (.pt)\n",
            "    for mdir in [Path('/kaggle/working/models'), REPO / 'models', REPO / 'output' / 'models', Path('models')]:\n",
            "        if mdir.is_dir() and list(mdir.glob('*.pt')):\n",
            "            print(f'Uploading checkpoint weights from {mdir}...')\n",
            "            api.upload_folder(\n",
            "                folder_path=str(mdir),\n",
            "                repo_id=HF_REPO_ID,\n",
            "                path_in_repo='models',\n",
            "                allow_patterns='*.pt'\n",
            "            )\n",
            "            print(f'Uploaded {len(list(mdir.glob(\"*.pt\")))} checkpoint(s).')\n",
            "            break\n",
            "    \n",
            "    # 2. Upload run metadata and metrics\n",
            "    for name in ['config.json', 'metrics.json', 'history.json']:\n",
            "        for sdir in [Path('/kaggle/working'), REPO, REPO / 'output', Path('.')]:\n",
            "            f = sdir / name\n",
            "            if f.is_file():\n",
            "                print(f'Uploading {name}...')\n",
            "                api.upload_file(path_or_fileobj=str(f), path_in_repo=name, repo_id=HF_REPO_ID)\n",
            "                break\n",
            "    \n",
            "    # 3. Model Card README\n",
            "    card_text = (\n",
            "        '---\\n'\n",
            "        'tags:\\n- pytorch\\n- bert\\n- compositionality\\n- contrastive-learning\\n- wep-infonce\\n'\n",
            "        '---\\n\\n'\n",
            "        '# MoTune mmBERT with Within-Exit Partitioned InfoNCE (WEP-InfoNCE)\\n\\n'\n",
            "        'Trained checkpoints, metrics, and configuration artifacts for Two-Stream mmBERT with WEP-InfoNCE.\\n\\n'\n",
            "        f'- **Temperature (tau)**: {OVERRIDES.get(\"wep_tau\", \"0.10\")}\\n'\n",
            "        f'- **Loss Weight**: {OVERRIDES.get(\"wep_weight\", \"0.08\")}\\n'\n",
            "        f'- **Base Config**: `{CONFIG_FILE}`\\n'\n",
            "    )\n",
            "    api.upload_file(\n",
            "        path_or_fileobj=card_text.encode('utf-8'),\n",
            "        path_in_repo='README.md',\n",
            "        repo_id=HF_REPO_ID\n",
            "    )\n",
            "    print(f'\\n>>> All weights and artifacts successfully uploaded to: https://huggingface.co/{HF_REPO_ID}')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CELL 6: (Optional) Score Trial Lineages and Generate Submission Zip\n",
            "import json, zipfile, torch\n",
            "from pathlib import Path\n",
            "from torch.utils.data import DataLoader\n",
            "from scipy.stats import spearmanr\n",
            "\n",
            "work = Path('/kaggle/working')\n",
            "ckpt = None\n",
            "for cand in [work / 'models' / 'best.pt', REPO / 'models' / 'best.pt', Path('models/best.pt')]:\n",
            "    if cand.is_file():\n",
            "        ckpt = cand\n",
            "        break\n",
            "\n",
            "if not ckpt:\n",
            "    print('No models/best.pt found. Skipping trial evaluation.')\n",
            "else:\n",
            "    print(f'Scoring trial data with best checkpoint: {ckpt}')\n",
            "    sys.path.insert(0, str(REPO))\n",
            "    from src.config import Config\n",
            "    from src.pipeline import _tokenizer\n",
            "    from src.data import load_trial, CompDataset, collate_comp\n",
            "    from src.model import apply_lora, build_model\n",
            "    from src.train import evaluate\n",
            "    import logging\n",
            "    \n",
            "    cfg_p = work / 'config.json' if (work / 'config.json').is_file() else REPO / 'config.json'\n",
            "    cfg = Config() if not cfg_p.is_file() else Config(**json.loads(cfg_p.read_text(encoding='utf-8')))\n",
            "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "    tok = _tokenizer(cfg, logging.getLogger('trial'))\n",
            "    \n",
            "    model = build_model(cfg, device)\n",
            "    apply_lora(model, rank=cfg.lora_rank, alpha=cfg.lora_alpha, dropout=cfg.lora_dropout,\n",
            "               targets=cfg.lora_targets, from_layer=cfg.lora_from_layer)\n",
            "    model.load_state_dict(torch.load(ckpt, map_location=device))\n",
            "    model.eval()\n",
            "    \n",
            "    sub = work / 'submission'\n",
            "    sub.mkdir(parents=True, exist_ok=True)\n",
            "    lineage = load_trial(cfg)\n",
            "    for key, rows in lineage.items():\n",
            "        ds = CompDataset(rows, tok, max_len=cfg.max_context_length, proto_stream=cfg.proto_stream)\n",
            "        loader = DataLoader(ds, batch_size=64, shuffle=False, collate_fn=collate_comp)\n",
            "        mp, hp, pp, my, hy, mask = evaluate(model, loader, device, return_all=True, return_pv=True)\n",
            "        pv = bool(rows[0]['is_pv'])\n",
            "        score = pp if pv else mp\n",
            "        lines = []\n",
            "        for r, pm, ph, sc in zip(rows, mp, hp, score):\n",
            "            if pv:\n",
            "                lines.append(f\"{r['context_id']}\\t{float(sc):.4f}\")\n",
            "            else:\n",
            "                lines.append(f\"{r['context_id']}\\t{float(pm):.4f}\\t{float(ph):.4f}\")\n",
            "        (sub / f'{key}-pred.tsv').write_text('\\n'.join(lines), encoding='utf-8')\n",
            "        print(f'{key}: {len(rows)} rows scored.')\n",
            "    \n",
            "    zip_path = work / 'submission.zip'\n",
            "    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:\n",
            "        for f in sorted(sub.glob('*-pred.tsv')):\n",
            "            zf.write(f, arcname=f.name)\n",
            "    print('Saved zipped submission archive:', zip_path)\n"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.12"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = Path("notebooks/kaggle_train_wep_infonce.ipynb")
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(json.dumps(nb, indent=2), encoding="utf-8")
print("Wrote notebook to:", out_path)
